apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: employee
  name: employee
spec:
  replicas: 1
  selector:
    matchLabels:
      run: employee
  template:
    metadata:
      labels:
        run: employee
    spec:
      serviceAccountName: chaos
      containers:
        - image: jayaram269/employee
          name: employee
          ports:
            - containerPort: 8080
              protocol: TCP

---

# APP SERVICE

apiVersion: v1
kind: Service
metadata:
  labels:
    run: employee
  name: employee
spec:
  ports:
    - port: 8080
