server:
  port: 9090

management:
  endpoints:
    web:
      exposure:
        include: '*'
zuul:
  routes:
    department:
      path: /department/**
      serviceId: department
      
    employee:
      path: /employee/**
      serviceId: employee
      
    organization:
      path: /organization/**   
      serviceId: organization
         