server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    department:
      path: /department/**
      serviceId: department
      
    employee:
      path: /employee/**
      serviceId: employee
      
    organization:
      path: /organization/**   
      serviceId: organization
         