apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: organization
  name: organization
spec:
  replicas: 1
  selector:
    matchLabels:
      run: organization
  template:
    metadata:
      labels:
        run: organization
    spec:
      serviceAccountName: chaos
      containers:
        - image: jayaram269/organization
          name: organization
          ports:
            - containerPort: 8080
              protocol: TCP

---

# APP SERVICE

apiVersion: v1
kind: Service
metadata:
  labels:
    run: organization
  name: organization
spec:
  ports:
    - port: 8080
