apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: department
  name: department
spec:
  replicas: 1
  selector:
    matchLabels:
      run: department
  template:
    metadata:
      labels:
        run: department
    spec:
      serviceAccountName: chaos
      containers:
        - image: jayaram269/department
          name: department
          ports:
            - containerPort: 8080
              protocol: TCP

---

# APP SERVICE

apiVersion: v1
kind: Service
metadata:
  labels:
    run: department
  name: department
spec:
  ports:
    - port: 8080
