apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: gateway
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      run: gateway
  template:
    metadata:
      labels:
        run: gateway
    spec:
      serviceAccountName: chaos
      containers:
        - image: jayaram269/gateway
          name: organization
          ports:
            - containerPort: 8080
              protocol: TCP

---

# APP SERVICE

apiVersion: v1
kind: Service
metadata:
  labels:
    run: gateway
  name: gateway
spec:
  ports:
    - port: 8080
